apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby-deployment
  labels:
    app: emby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
#      securityContext:
#        fsGroup: 1000
      imagePullSecrets:
        - name: regcred
      containers:
        - name: emby
          image: "emby/embyserver:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8096  # Default emby port
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Africa/Johannesburg"    # Set your timezone
          volumeMounts:
            - name: emby-dir
              mountPath: /config
            - name: emby-videos
              mountPath: /mnt/home_nas/Videos
      volumes:
        - name: emby-dir
          hostPath:
            path: /opt/docker/media_stack/emby/config
            type: DirectoryOrCreate
        - name: emby-videos
          hostPath:
            path: /mnt/home_nas/Videos
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: emby-service
spec:
  type: NodePort
  selector:
    app: emby
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30996  # Exposed port on the node
