apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr-deployment
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - name: flaresolverr
          image: "ghcr.io/flaresolverr/flaresolverr:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8191  # Default flaresolverr port
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Africa/Johannesburg"    # Set your timezone
          volumeMounts:
            - name: flaresolverr-dir
              mountPath: /config
      volumes:
        - name: flaresolverr-dir
          hostPath:
            path: /opt/docker/media_stack/flaresolverr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-service
spec:
  type: NodePort
  selector:
    app: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191
      nodePort: 30191  # Exposed port on the node
