apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        env:
        - name: SIGNUPS_ALLOWED
          value: "false" 
        - name: DOMAIN
          value: "https://pwm.nasson.co.za"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vaultwarden-data
          mountPath: /data
      volumes:
      - name: vaultwarden-data
        hostPath:
          path: /opt/docker/vaultwarden/vw-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-https
  namespace: vaultwarden
spec:
  entryPoints: [websecure]
  routes:
  - kind: Rule
    match: Host(`pwm.nasson.co.za`)
    services:
    - name: vaultwarden-service
      port: 80
  tls: {}
