apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: mailcow-transport
  namespace: kube-system
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: mailcow-web-backend
  namespace: kube-system
spec:
  ports:
    - name: https-internal
      port: 443           # This is the port Traefik looks for
      targetPort: 9443    # This is the port on the Docker host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mailcow-web-backend # MUST match Service name exactly
  namespace: kube-system
subsets:
  - addresses:
      - ip: 172.17.0.1
    ports:
      - name: https-internal
        port: 9443
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mailcow-web-https
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`mailcow.nasson.co.za`)
    services:
    - name: mailcow-web-backend
      port: 443           # MUST match the Service port above
      scheme: https
      serversTransport: mailcow-transport
  tls: {}
