apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true" # Forces TLS mode
spec:
  tls:
  - hosts:
      - argo.nasson.co.za # This MUST match the host below exactly
    secretName: nasson-wildcard-tls
  rules:
  - host: argo.nasson.co.za
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https