apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argo.nasson.co.za`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          scheme: https # ArgoCD internal traffic is HTTPS
  tls:
    secretName: nasson-wildcard-tls
